version: '3.8'

services:

  front-end:
      container_name: test-app-front-end
      build:
        context: ./front-end
      ports:
        - "3001:3000"
      depends_on:
        - back-end
        
  db:
    image: mysql:latest
    container_name: test-app-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test-app-db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: test-app-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db

  back-end:
    container_name: test-app-back-end
    build:
      context: ./back-end
    ports:
      - "4001:4000"
    environment:
      DB_HOST: db
    depends_on:
      - db
    env_file:
      - .env.docker

volumes:
  db-data:
    driver: local
